import { NextRequest, NextResponse } from "next/server";
import { paymentRepository } from "@/features/payment/repositories/payment.repository";

/**
 * GET /api/payment/token-info?token=xxx
 * NO auth required — called by the payment app to retrieve payment details
 * using a one-time token generated by /api/payment/initiate-redirect.
 *
 * Returns payment details needed by the payment app to open Razorpay checkout.
 * Returns 404 if token doesn't exist, 410 if expired or already used.
 */
export async function GET(request: NextRequest) {
  // CORS — allow payment app origin
  const paymentAppUrl = process.env.PAYMENT_APP_URL || "http://localhost:3001";

  const corsHeaders = {
    "Access-Control-Allow-Origin": paymentAppUrl,
    "Access-Control-Allow-Methods": "GET, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
  };

  const token = request.nextUrl.searchParams.get("token");
  if (!token || token.length < 32) {
    return NextResponse.json(
      { success: false, message: "Missing or invalid token" },
      { status: 400, headers: corsHeaders }
    );
  }

  const tokenData = await paymentRepository.findValidToken(token);

  if (!tokenData) {
    return NextResponse.json(
      {
        success: false,
        message: "Token is invalid, expired, or already used. Please restart checkout.",
        code: "TOKEN_INVALID",
      },
      { status: 410, headers: corsHeaders }
    );
  }

  return NextResponse.json(
    {
      success: true,
      data: {
        razorpayOrderId: tokenData.razorpayOrderId,
        amount: Math.round(tokenData.amount * 100), // paise
        currency: tokenData.currency,
        keyId: tokenData.keyId,
        orderNumber: tokenData.orderNumber,
        token: tokenData.token,
        expiresInMs: 30 * 60 * 1000,
      },
    },
    { status: 200, headers: corsHeaders }
  );
}

export async function OPTIONS() {
  const paymentAppUrl = process.env.PAYMENT_APP_URL || "http://localhost:3001";
  return new NextResponse(null, {
    status: 204,
    headers: {
      "Access-Control-Allow-Origin": paymentAppUrl,
      "Access-Control-Allow-Methods": "GET, OPTIONS",
      "Access-Control-Allow-Headers": "Content-Type",
    },
  });
}
